version: '3.7'

services:
  webapp:
    build: . 
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py loaddata 0001_seed.json &&
                    python manage.py runserver "0.0.0.0:8000""
    volumes:
      - .:/webapp
      - static_volume:/home/app/webapp/static
    image: simplesearch_app
    expose: 
      - 8000
    ports:
      - "8000:8000"

  db:
    image: postgres:15.2-alpine 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=simplesearchdb
      - PGPORT=5432
      - POSTGRES_USER=postgres

volumes:
  postgres:
  static_volume:

networks:
  default:
    driver: bridge
